from __future__ import annotations

IMPORT_ERROR_CODES: dict[str, str] = {
    "TAG_INVALID": "TAG_INVALID",
    "PARSER_SCRIPT_NOT_FOUND": "PARSER_SCRIPT_NOT_FOUND",
    "PARSER_SCRIPT_RISK": "PARSER_SCRIPT_RISK",
    "PARSER_SCRIPT_TIMEOUT": "PARSER_SCRIPT_TIMEOUT",
    "PARSER_SCRIPT_RUNTIME_ERROR": "PARSER_SCRIPT_RUNTIME_ERROR",
    "PARSE_RESULT_SCHEMA_INVALID": "PARSE_RESULT_SCHEMA_INVALID",
    "INDEX_BINDING_CONFLICT": "INDEX_BINDING_CONFLICT",
    "VECTOR_MODEL_PREPARE_FAILED": "VECTOR_MODEL_PREPARE_FAILED",
}