# Auto-generated by pre-commit hook
from bible.api.knowledge import router as knowledge_router
from bible.api.system import router as system_router
from bible.api.search import router as search_router

__all__ = [
    "knowledge_router",
    "system_router",
    "search_router",
]