# Auto-generated by pre-commit hook
from bible.api.knowledge import router as knowledge_router
from bible.api.system import router as system_router

__all__ = [
    "knowledge_router",
    "system_router",
]