# Auto-generated by pre-commit hook
from bible.api.control import control_router
from bible.api.knowledge import router as knowledge_router
from bible.api.search import search_router
from bible.api.system import router as system_router

__all__ = [
    "control_router",
    "knowledge_router",
    "search_router",
    "system_router",
]